### ISSUE TITLE
 (<unknown>): mapping values are not allowed

### ISSUE THREAD

**Issue by D-Alex** [orocos-toolchain/autoproj#4]
the commit https://github.com/orocos-toolchain/autoproj/commit/56737264b68a7ca14b22137edff6e9ce268b928f breaks compatibility with ruby 2.0.0p384

Error message:

```
 /home/aduda/dev/seabotix/autoproj/remotes/orocos.toolchain/orocos.osdeps-ruby20:
 (<unknown>): mapping values are not allowed in this context at line 6 column 17
```

The following seems to work:

```
ubuntu:
    - '14.04': ruby-nokogiri
    - default:
         - gem: nokogiri
         - osdep: libxml2
         - osdep: libxslt
```
